import React from 'react'

export default function SecondSection() {
    return (
        <>
            <div className='second-section'>
                <div className="container mt-5">
                    <div className="row mx-0 align-items-center">
                        <div className="col-lg-6 col-12">
                            <img src="assets/images/photo.webp" className='w-100' alt="" />
                        </div>
                        <div className="col-lg-6 col-12">
                            <div className="d-flex align-items-center">
                                <span className="they">They</span>
                                <span className='fs-5 ps-2'>say that you are the average of the five</span>
                            </div>
                            <p className='fs-5'>
                                people you spend the most time with and that growth is rarely by chance. This collective will expose you to exceptional individuals for collaboration and mutually beneficial relationships. It’s easy to understand the importance and value in networking with the people that truly want the best for you.
                            </p>
                            <p className='fs-5'>
                                The foundation of the collective is to launch members to the next level by focussing obsessively on improving their knowledge, network, net worth, and life experience.
                            </p>
                            <p className='fs-5'>
                                Your NFT will grant you access to post-sale deliverables and a community that was created out of a love for business, financial security, art, fashion, technology, and design.
                            </p>
                            <p className="fs-5">
                                Similar to Shark Tank and Dragons Den, 'The Bear Cave' will use community funds to invest into businesses owned by the NFT holders. A share of the profits generated by those businesses will be owned by the community and generate a continuous revenue stream for the community wallet. Profit-related kickback will be distributed to Graffiti Bear Holders at regular intervals.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
